site_name: acceleratedWEKA
site_url: https://Waikato.github.io/acceleratedWEKA
repo_name: Waikato/acceleratedWEKA
repo_url: https://github.com/Waikato/acceleratedWEKA
markdown_extensions:
  - attr_list
  - md_in_html
nav:
  - Home: index.md
  - User Guide:
    - Installation: user_guide/installation.md
    - Architecture: user_guide/architecture.md
    - Getting Started: user_guide/getting_started.md
    - Features: user_guide/features.md
    - Examples: user_guide/examples.md
  - About: about.md
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.expand   
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default


      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
